[settings]
go_set_goroot = true

[tools]
## https://go.dev/doc/devel/release
go = '1.25'
## https://github.com/goreleaser/goreleaser/releases
"goreleaser" = '2'
## https://github.com/golangci/golangci-lint/releases
"golangci-lint" = '2'

## https://github.com/cue-lang/cue/releases
"cue" = 'latest'
